exp_id: exp009

optimizer:
    name: Adam
    params:
        lr: 1.0e-3

scheduler:
    name: HalfCosineAnnealingLR
    params:
        T_max: 10

train:
    num_epochs: 200
    precision: 32
    mixup: True

model:
    name: HarDNet
    params:
        arch: 68
        num_classes: 10
    resume_from:
    
seed: 0